package miniJava.SyntacticAnalyzer;

public enum TokenKind {ID, NUM, MINUS, UNOP, BINOP, KEYWORD, EOT, 
	LPAREN, RPAREN, LCURLY, RCURLY, LBRACK, RBRACK, COMMA, SEMICOLON, PERIOD, ERROR,
	ASSIGN, LINECOMMENT, BLOCKCOMMENT,
	
	CLASS, RETURN, PUBLIC, PRIVATE, STATIC, VOID, INT, BOOLEAN, THIS, IF, ELSE, 
	WHILE, TRUE, FALSE, NEW,
	
	OR, AND, EQUAL, NOTEQUAL, LTEQ, LT, GT, GTEQ, PLUS, TIMES, DIVIDE
} 
